<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BumdesSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
        'desa' => 'Aeng Baja Kenek',
        'nama_bumdes' => 'BUM DESA BINTANG SURYA',
        'direktur' => 'Chairul Anam',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Aeng Baja Raja',
        'nama_bumdes' => 'BUM DESA MAKMUR JAYA ABR',
        'direktur' => 'Sufyan Hadi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Aeng Dake',
        'nama_bumdes' => 'BUM DESA MAKMUR JAYA',
        'direktur' => 'Suhaimi',
        'status_hukum' => 'Perbaikan Nama',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Aeng Panas',
        'nama_bumdes' => 'BUM DESA PERMATA IBU',
        'direktur' => 'Syaiful Bahri, SE. MM',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Aenganyar',
        'nama_bumdes' => 'BUM DESA FAJAR REMBULAN',
        'direktur' => 'Anwar Sidqi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Aengmerah',
        'nama_bumdes' => 'BUM DESA AMER JAYA',
        'direktur' => 'Abd. Rahman',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Aengtongtong',
        'nama_bumdes' => 'BUM DESA ARYA PUSAKA',
        'direktur' => 'Moh. Ikmal',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Alas Malang',
        'nama_bumdes' => 'BUM DESA SUMBER REZEKI',
        'direktur' => 'Lilik Ishlahatus Shalehah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Ambunten Barat',
        'nama_bumdes' => 'BUM DESA DHEMAR ODHI',
        'direktur' => 'Sukdik',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Ambunten Tengah',
        'nama_bumdes' => 'BUM DESA CANDRA KIRANA',
        'direktur' => 'Ahmad Yamin, SE',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Ambunten Timur',
        'nama_bumdes' => 'BUM DESA BAHTERA BERKAH SEJAHTERA',
        'direktur' => 'Drs. Zainuddin',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Andulang',
        'nama_bumdes' => 'BUM DESA BUNGA AGUNG',
        'direktur' => 'Pausi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Angkatan',
        'nama_bumdes' => 'BUM DESA LANON MARITIM',
        'direktur' => 'Iswanto',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Angon-Angon',
        'nama_bumdes' => 'BUM DESA KARYA PEMUDA',
        'direktur' => 'Sulaiman',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Arjasa',
        'nama_bumdes' => 'BUM DESA BINA KARYA',
        'direktur' => 'Mukhlis',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Baban',
        'nama_bumdes' => 'BUM DESA SUMBER REJEKI',
        'direktur' => 'Ach. Junaidi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Babbalan',
        'nama_bumdes' => 'BUM DESA MAJU SEJAHTERA',
        'direktur' => 'Fathol Faruq Irawan',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Badur',
        'nama_bumdes' => 'BUM DESA CAHAYA BARU',
        'direktur' => 'Ahmad Hosaini',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bakeong',
        'nama_bumdes' => 'BUM DESA MANDIRI',
        'direktur' => 'Taufikur Rahman',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Banaresep Barat',
        'nama_bumdes' => 'BUM DESA MAWAR',
        'direktur' => 'Atikurrahman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Banaresep Timur',
        'nama_bumdes' => 'BUM DESA MAHKOTA',
        'direktur' => 'Maulidi Amsi',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Banasare',
        'nama_bumdes' => 'BUM DESA POTRE KONENG',
        'direktur' => 'Imam Fadli Rahman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Banbaru',
        'nama_bumdes' => 'BUM DESA SUMBER REJEKI',
        'direktur' => 'Edi Sugianto',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bancamara',
        'nama_bumdes' => 'BUM DESA GINJIR ANGIN',
        'direktur' => 'Irno',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BELUM ISI',
    ],
    [
        'desa' => 'Bangkal',
        'nama_bumdes' => 'BUM DESA BERKARYA',
        'direktur' => 'Moh. Kurdi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Banjar Barat',
        'nama_bumdes' => 'BUM DESA BUNGA RAMPAI',
        'direktur' => 'Abdus Sufi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Banjar Timur',
        'nama_bumdes' => 'BUM DESA DUTA WARGA',
        'direktur' => 'Abd. Rahim',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Banmaleng',
        'nama_bumdes' => 'BUM DESA SUMBER SEJAHTERA',
        'direktur' => 'Ramzi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => "Banra'as",
        'nama_bumdes' => 'BUM DESA BERSATU',
        'direktur' => 'Misnadi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Bantelan',
        'nama_bumdes' => 'BUM DESA MOGA BERKAH',
        'direktur' => 'Azisa',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Banuaju Barat',
        'nama_bumdes' => 'BUM DESA BANYU URIP',
        'direktur' => 'Abd. Rasyid',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Banuaju Timur',
        'nama_bumdes' => 'BUM DESA KARTIKA JAYA',
        'direktur' => 'Durrotun Hasanah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Basoka',
        'nama_bumdes' => 'BUM DESA JAYA ABADI',
        'direktur' => 'Saiful Akbar',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bataal Barat',
        'nama_bumdes' => 'BUM DESA SUMBER EMPAT',
        'direktur' => 'Zulfah',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Bataal Timur',
        'nama_bumdes' => 'BUM DESA SUMBER MAKMUR',
        'direktur' => 'Moh. Fadali',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batang-Batang Daya',
        'nama_bumdes' => 'BUM DESA AMANAH',
        'direktur' => '-',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batang-Batang Laok',
        'nama_bumdes' => 'BUM DESA BAROKAH',
        'direktur' => 'Marjuddin',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Bates',
        'nama_bumdes' => 'BUM DESA PRABU ANOM',
        'direktur' => 'Bustanul Arifin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batuan',
        'nama_bumdes' => 'BUM DESA BATU PERMATA',
        'direktur' => 'Fajar Budiono',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batubellah Barat',
        'nama_bumdes' => 'BUM DESA GARUDA EMAS',
        'direktur' => 'Ali Wafa',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batubellah Timur',
        'nama_bumdes' => 'BUM DESA MOGO JOYO',
        'direktur' => 'Habibul Mohtar',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batudinding',
        'nama_bumdes' => 'BUM DESA BAROKAH JAYA',
        'direktur' => 'Akh. Taksawi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batuputih',
        'nama_bumdes' => 'BUM DESA SEHATI',
        'direktur' => 'Matnin, S.Pd.I',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batuputih Daya',
        'nama_bumdes' => 'BUM DESA BADAY JAYA',
        'direktur' => 'Ach. Zainul Hasan Arobi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batuputih Kenek',
        'nama_bumdes' => 'BUM DESA ANTOS',
        'direktur' => 'Holik, S.Pd.I',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Batuputih Laok',
        'nama_bumdes' => 'BUM DESA BERKAH',
        'direktur' => 'Moh. Siddiq',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Belluk Ares',
        'nama_bumdes' => 'BUM DESA SAKINAH',
        'direktur' => 'Hosniyatun',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Belluk Kenek',
        'nama_bumdes' => 'BUM DESA SEJAHTERA',
        'direktur' => 'Sholehoddin',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Belluk Raja',
        'nama_bumdes' => 'BUM DESA RIZQUNAH',
        'direktur' => 'Rumiyati',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bicabbi',
        'nama_bumdes' => 'BUM DESA PANGESTOH',
        'direktur' => 'Ahmat Yanto',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bilangan',
        'nama_bumdes' => 'BUM DESA SUMBER MAKMUR',
        'direktur' => 'Nurfaizah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bilis-Bilis',
        'nama_bumdes' => 'BUM DESA LOMBI TELER',
        'direktur' => 'Guradin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Billapora Barat',
        'nama_bumdes' => 'BUM DESA JHUNG ROJHUNG',
        'direktur' => 'Abd. Shakir',
        'status_hukum' => 'Pendaftaran Badan Hukum',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Billapora Rebba',
        'nama_bumdes' => 'BUM DESA CAHAYA BILAPORA REBBA',
        'direktur' => 'Moh. Hafid',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Billapora Timur',
        'nama_bumdes' => 'BUM DESA JAYA BAROKAH',
        'direktur' => 'Ahmad Junaidi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bluto',
        'nama_bumdes' => 'BUM DESA BHAKTI ANDALAN',
        'direktur' => '-',
        'status_hukum' => 'Perbaikan Nama',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Bragung',
        'nama_bumdes' => 'BUM DESA SRIKANDI',
        'direktur' => 'Ferdy Rahman Hidayat, SH',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Braji',
        'nama_bumdes' => 'BUM DESA LANCAR JAYA',
        'direktur' => 'Miftahul Jinan',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Brakas',
        'nama_bumdes' => 'BUM DESA BRAKAS JAYA ABADI', 
        'direktur' => 'Monawi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bringin',
        'nama_bumdes' => 'BUM DESA BRINGIN HEBAT',
        'direktur' => 'Matwaji',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bringsang',
        'nama_bumdes' => 'BUM DESA SERUNAI JINGGA',
        'direktur' => '',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bukabu',
        'nama_bumdes' => 'BUM DESA NATHA PRAJA',
        'direktur' => 'Nurul Asmi',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => "Bulla'an",
        'nama_bumdes' => "BUM DESA MAHKOTA JAYA",
        'direktur' => 'Susmiyati',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bumbungan',
        'nama_bumdes' => 'BUM DESA BAROKAH', 
        'direktur' => 'Susiyanto',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Bunbarat',
        'nama_bumdes' => 'BUM DESA SERBAGUNA',
        'direktur' => 'Moh. Sofwan',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bungin-Bungin',
        'nama_bumdes' => 'BUM DESA CAHAYA CETIR',
        'direktur' => 'Mahfud',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Bunpenang',
        'nama_bumdes' => 'BUM DESA PINANG MAS',
        'direktur' => 'Mohammad Hotib',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Cabbiya',
        'nama_bumdes' => 'BUM DESA CABBIYA BANGKIT',
        'direktur' => 'Abdur Rahman',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Campaka',
        'nama_bumdes' => 'BUM DESA BUNGA CEMPAKA',
        'direktur' => 'Lafifah, S.Pd.I, MM',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Campor Barat',
        'nama_bumdes' => 'BUM DESA MAKMUR JAYA',
        'direktur' => 'Hazaimah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Campor Timur',
        'nama_bumdes' => 'BUM DESA MELATI INDAH',
        'direktur' => 'Zainabun',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Candi',
        'nama_bumdes' => 'BUM DESA CANDI PUTRA',
        'direktur' => 'Ike Gustina Anisa Fitri',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Cangkramaan',
        'nama_bumdes' => 'BUM DESA SEJAHTERA',
        'direktur' => 'Sahidin',
        'status_hukum' => 'Perbaikan Nama',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Cangkreng',
        'nama_bumdes' => 'BUM DESA AMANAH SUMBER RIZQY',
        'direktur' => 'Moh. Saleh',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BELUM ISI',
    ],
    [
        'desa' => 'Daandung',
        'nama_bumdes' => 'BUM DESA MUTIARA BAKTI',
        'direktur' => 'Ali Sahiuddin Kasim',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Dapenda',
        'nama_bumdes' => 'BUM DESA CEMARA UDANG',
        'direktur' => 'Choirul Umam',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Daramista',
        'nama_bumdes' => 'BUM DESA MELATI',
        'direktur' => 'Adisti Olivia W',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Dasuk Barat',
        'nama_bumdes' => 'BUM DESA SUMBER REJEKI',
        'direktur' => 'Ebadillah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Dasuk Laok',
        'nama_bumdes' => 'BUM DESA MANDIRI SEJAHTERA',
        'direktur' => 'Afifuddin Hafaz',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Dasuk Timur',
        'nama_bumdes' => 'BUM DESA AL FARA',
        'direktur' => 'Abdullah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Duko',
        'kecamatan' => 'Arjasa',
        'nama_bumdes' => 'BUM DESA DELIA UTAMA DUKO ABADI',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Duko',
        'kecamatan' => 'Rubaru',
        'nama_bumdes' => 'BUM DESA BUKIT TANJUNG',
        'direktur' => 'M. Jauzi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Dungkek',
        'nama_bumdes' => 'BUM DESA ANUGERAH',
        'direktur' => '-',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Ellak Daya',
        'nama_bumdes' => 'BUM DESA KASIH BUNDA',
        'direktur' => 'Masturi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Ellak Laok',
        'nama_bumdes' => 'BUM DESA INSAN BAROKAH',
        'direktur' => 'Siswandi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Errabu',
        'nama_bumdes' => 'BUM DESA SUMBER SURYA',
        'direktur' => 'Ari Ashari',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Essang',
        'nama_bumdes' => 'BUM DESA ESSANG BERSATU', 
        'direktur' => 'Sari Maghfiroh',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Gadding',
        'nama_bumdes' => 'BUM DESA JAYA AGUNG',
        'direktur' => 'Syakrani',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Gadu Barat',
        'nama_bumdes' => 'BUM DESA CAHAYA ABADI',
        'direktur' => 'Fauzi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Gadu Timur',
        'nama_bumdes' => 'BUM DESA SUMBER ANYAR',
        'direktur' => 'Zahro Ulfa',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Galis',
        'nama_bumdes' => 'BUM DESA MAKMUR',
        'direktur' => 'Sadam Husen',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Galugur',
        'nama_bumdes' => 'BUM DESA ANUGERAH DESA',
        'direktur' => 'Ach. Fauzi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Ganding',
        'nama_bumdes' => 'BUM DESA WANGI',
        'direktur' => 'Zubaidi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Gapura Barat',
        'nama_bumdes' => 'BUM DESA MITRA RAKYAT',
        'direktur' => '-',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Gapura Tengah',
        'nama_bumdes' => 'BUM DESA PUTRI KLENTANG',
        'direktur' => 'Al Mahmudi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Gapura Timur',
        'nama_bumdes' => 'BUM DESA YALI',
        'direktur' => 'Mas odi, S.Pd.I',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Gapurana',
        'nama_bumdes' => 'BUM DESA GAPURANA JAYA', 
        'direktur' => 'Danay Khairur Rasyidy',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Gayam',
        'nama_bumdes' => 'BUM DESA SERUNI',
        'direktur' => 'Marwatus Deni',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Gedang-Gedang',
        'nama_bumdes' => 'BUM DESA SEKAR TANJUNG',
        'direktur' => 'Muhammad Sadili Efendi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Gedugan',
        'nama_bumdes' => 'BUM DESA MAWAR MERAH',
        'direktur' => 'Siti Rukayya',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Gedungan',
        'nama_bumdes' => 'BUM DESA SUMBER MAKMUR',
        'direktur' => 'Iskandar',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Gelaman',
        'nama_bumdes' => 'BUM DESA GELAMAN JAYA', 
        'direktur' => 'Darsono',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Gendang Barat',
        'nama_bumdes' => 'BUM DESA HARAPAN JAYA MAJU',
        'direktur' => 'Suprapto',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Gendang Timur',
        'nama_bumdes' => 'BUM DESA BUNGA TERATAI',
        'direktur' => 'Mohrida',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Gersik Putih',
        'nama_bumdes' => 'BUM DESA DINDA',
        'direktur' => 'Padali',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Gilang',
        'nama_bumdes' => 'BUM DESA GILANG GEMILANG', 
        'direktur' => 'Desiyanti',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Gingging',
        'nama_bumdes' => 'BUM DESA PELITA MUDA',
        'direktur' => 'Mailan',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Grujugan',
        'nama_bumdes' => 'BUM DESA SOEJHAKRA',
        'direktur' => 'Satnawi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Guluk Manjung',
        'nama_bumdes' => 'BUM DESA BINTANG KEJORA',
        'direktur' => 'Syaiful Islam',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Guluk-Guluk',
        'nama_bumdes' => 'BUM DESA MAJU BERSAMA',
        'direktur' => 'Faydirrachman',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Gunggung',
        'nama_bumdes' => 'BUM DESA PUTRA AGUNG',
        'direktur' => 'Sarkawi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Guwa-Guwa',
        'nama_bumdes' => 'BUM DESA BUMDESA KARAENG MANDIRI',
        'direktur' => 'Sarkawi',
        'status_hukum' => 'Perbaikan Nama',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Jaddung',
        'nama_bumdes' => 'BUM DESA CITRA MANDIRI',
        'direktur' => 'Syahrawi',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Jadung',
        'nama_bumdes' => 'BUM DESA HIKMAH',
        'direktur' => 'Agus Saeri',
        'status_hukum' => 'Pendaftaran Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Jambu',
        'nama_bumdes' => 'BUM DESA JAMBU SATU', 
        'direktur' => 'Ghozi Mubarak',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Jambuir',
        'nama_bumdes' => 'BUM DESA GAJAH MADA',
        'direktur' => 'Fitriyana',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Jangkong',
        'nama_bumdes' => 'BUM DESA MARGIYU',
        'direktur' => 'Johan Nihru',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Jate',
        'nama_bumdes' => 'BUM DESA SEJATI',
        'direktur' => 'Buridin',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Jelbudan',
        'nama_bumdes' => 'BUM DESA KARYA SEJAHTERA',
        'direktur' => 'Moh. Syamsul Arifin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Jenangger',
        'nama_bumdes' => 'BUM DESA POTRE JENANG',
        'direktur' => 'Fajar Supriyanto',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Juluk',
        'nama_bumdes' => 'BUM DESA ANUGERAH JAYA',
        'direktur' => 'Junaidi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Jungkat',
        'nama_bumdes' => 'BUM DESA BUMI PERTIWI',
        'direktur' => 'Subaidi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Juruan Daya',
        'nama_bumdes' => 'BUM DESA TERATAI',
        'direktur' => 'Rukiyah, S.Pd',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Juruan Laok',
        'nama_bumdes' => 'BUM DESA JUPITER',
        'direktur' => 'Qurratul Aini',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kacongan',
        'nama_bumdes' => 'BUM DESA KACONGAN BERSATU', 
        'direktur' => 'Saifur Rahman, S.Ag',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Kaduara Timur',
        'nama_bumdes' => 'BUM DESA GEMA BANGSA',
        'direktur' => 'Usma Efendi',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Kalebengan',
        'nama_bumdes' => 'BUM DESA NUSANTARA',
        'direktur' => 'Adlan',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kalianget Barat',
        'nama_bumdes' => 'BUM DESA SETIA MAKMUR',
        'direktur' => 'Sayuti Jalaluddin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Kalianget Timur',
        'nama_bumdes' => 'BUM DESA LESTARI',
        'direktur' => 'Joni Hidayat',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kalikatak',
        'nama_bumdes' => 'BUM DESA NIAGA RAKYAT BERKAH',
        'direktur' => 'Nur Atika',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kalinganyar',
        'nama_bumdes' => 'BUM DESA TUNAS MUDA JAYA',
        'direktur' => 'Sitti Hasiya',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Kalisangka',
        'nama_bumdes' => 'BUM DESA PANTAI INDAH',
        'direktur' => 'Rahmatullah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBEMBANG',
    ],
    [
        'desa' => 'Kalowang',
        'nama_bumdes' => 'BUM DESA MENTARI',
        'direktur' => 'Jubriyanto',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kambingan Barat',
        'nama_bumdes' => 'BUM DESA MAHKOTA KAMBAR',
        'direktur' => 'Muhammad Misbahudholam, AR',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kambingan Timur',
        'nama_bumdes' => 'BUM DESA SEJUTA DINAR',
        'direktur' => 'Lugman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kangayan',
        'nama_bumdes' => 'BUM DESA ASDA',
        'direktur' => 'Jahnal',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kapedi',
        'nama_bumdes' => 'BUM DESA JAYA PUTRA',
        'direktur' => 'Rindiyati',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Karang Campaka',
        'nama_bumdes' => 'BUM DESA MATAHARI CEMPAKA', 
        'direktur' => 'Yayuk Sri Wahyuni',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Karang Nangka',
        'nama_bumdes' => 'BUM DESA BUNGA SEROJA',
        'direktur' => 'Raudatul Jannah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Karang Tengah',
        'nama_bumdes' => 'BUM DESA KARANG TARUNA',
        'direktur' => 'Sugiyono',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Karangbudi',
        'nama_bumdes' => 'BUM DESA SERBAGUNA',
        'direktur' => 'Bambang Sutejo',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Karangnangka',
        'nama_bumdes' => 'BUM DESA RAESA JAYA',
        'direktur' => 'Satrawi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Karduluk',
        'nama_bumdes' => 'BUM DESA KARYA LESTARI',
        'direktur' => 'Khatibul Umam, M.Pd',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kasengan',
        'nama_bumdes' => 'BUM DESA TELAGA EMAS',
        'direktur' => 'Syamsul Kholis, SP',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kebunagung',
        'nama_bumdes' => 'BUM DESA GOA JERUK',
        'direktur' => 'Yudhatama',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Kebunan',
        'nama_bumdes' => 'BUM DESA MAWAR',
        'direktur' => 'Sugiono',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kebundadap Barat',
        'nama_bumdes' => 'BUM DESA RATU',
        'direktur' => 'Farid Prasojo',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kebundadap Timur',
        'nama_bumdes' => 'BUM DESA PASOPATI',
        'direktur' => 'Aji Nur Rahman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Kecer',
        'nama_bumdes' => 'BUM DESA TERA ATEH',
        'direktur' => 'Sufiyanto',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Keles',
        'nama_bumdes' => 'BUM DESA SERDADU',
        'direktur' => 'Masnidi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kerta Barat',
        'nama_bumdes' => 'BUM DESA KERTA JAYA MAKMUR', 
        'direktur' => 'Nurul Ma rifah Isnaini',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kerta Timur',
        'nama_bumdes' => 'BUM DESA KERTA JAYA', 
        'direktur' => 'Mutasmar',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Ketawang Daleman',
        'nama_bumdes' => 'BUM DESA DALEMAN JAYA', 
        'direktur' => 'Ach. Subairi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Ketawang Karay',
        'nama_bumdes' => 'BUM DESA BHAKTI IBU', 
        'direktur' => 'Achmad Jufri',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Ketawang Laok',
        'nama_bumdes' => 'BUM DESA MAJU JAYA', 
        'direktur' => '',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Ketawang Larangan',
        'nama_bumdes' => 'BUM DESA HARAPAN JAYA',
        'direktur' => 'Nur Hayati',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Ketupat',
        'nama_bumdes' => 'BUM DESA KETUPAT MANDIRI',
        'direktur' => 'Rusydi Asy ari',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kolo-Kolo',
        'nama_bumdes' => 'BUM DESA SURYA SAMUDRA',
        'direktur' => 'Aqilul Mufid',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Kolor',
        'nama_bumdes' => 'BUM DESA KURMA AJWA',
        'direktur' => 'Achmad Wahyudi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kolpo',
        'nama_bumdes' => 'BUM DESA MANDIRI',
        'direktur' => 'Moh. Marzuki',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Kombang',
        'nama_bumdes' => 'BUM DESA SIWALAN',
        'direktur' => 'Suhartatik',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Kropoh',
        'nama_bumdes' => 'BUM DESA KARYA UTAMA',
        'direktur' => 'Zainudin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Lalangon',
        'nama_bumdes' => 'BUM DESA PUTRI MANDIRI',
        'direktur' => 'Fitriyatul Jannah',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Langsar',
        'nama_bumdes' => 'BUM DESA JAYA BERKAH',
        'direktur' => 'Lathifah Hasan',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Laok Jang-jang',
        'nama_bumdes' => 'BUM DESA RUMAH BUNDA',
        'direktur' => 'Asrawi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Lapa Daya',
        'nama_bumdes' => 'BUM DESA BAROKAH JAYA',
        'direktur' => 'Fathor Rahman',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Lapa Laok',
        'nama_bumdes' => 'BUM DESA MAHKOTA NUSANTARA',
        'direktur' => 'H. Atmari',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Lapa Taman',
        'nama_bumdes' => 'BUM DESA JOKO THOLE',
        'direktur' => 'Ainul Yakin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Larangan Barma',
        'nama_bumdes' => 'BUM DESA BARMA AGUNG',
        'direktur' => 'Akhmad Haryono',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Larangan Kerta',
        'nama_bumdes' => 'BUM DESA SUKA MAJU',
        'direktur' => 'Samsuri',
        'status_hukum' => 'Pendaftaran Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Larangan Perreng',
        'nama_bumdes' => 'BUM DESA MITRA UTAMA',
        'direktur' => 'Achmad Sanusi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Lebeng Barat',
        'nama_bumdes' => 'BUM DESA KONROKON',
        'direktur' => 'Raudhatul Ingkiat',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Lebeng Timur',
        'nama_bumdes' => 'BUM DESA WAHANA SEJAHTERA',
        'direktur' => 'Sapraji Wijaya',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Legung Barat',
        'nama_bumdes' => 'BUM DESA LEGUNG BARAT MAKMUR', 
        'direktur' => 'Wirno',
        'status_hukum' => 'Pendaftaran Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Legung Timur',
        'nama_bumdes' => 'BUM DESA LE GONG JAYA',
        'direktur' => 'Sugiyanto',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Lembung Barat',
        'nama_bumdes' => 'BUM DESA NURUL IKHSAN TRANGGANO',
        'direktur' => 'Usmuni',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Lembung Timur',
        'nama_bumdes' => 'BUM DESA AMANAH',
        'direktur' => 'Ach. Taufiqur Rohman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BELUM ISI',
    ],
    [
        'desa' => 'Lenteng Barat',
        'nama_bumdes' => 'BUM DESA RODINDA',
        'direktur' => 'Achmad Lutfi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Lenteng Timur',
        'nama_bumdes' => 'BUM DESA HARUM',
        'direktur' => 'Ahmad Fawaid',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Lobuk',
        'nama_bumdes' => 'BUM DESA PELANGI NUSANTARA',
        'direktur' => 'Suparyono',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Lombang',
        'nama_bumdes' => 'BUM DESA CAHAYA LOMBANG', 
        'direktur' => 'Sudarsono',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Lombang',
        'nama_bumdes' => 'BUM DESA CEMARA UDANG',
        'direktur' => 'Silfana Noor Fauzza',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Longos',
        'nama_bumdes' => 'BUM DESA MERPATI',
        'direktur' => 'Tola udi',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Mandala',
        'nama_bumdes' => 'BUM DESA SEJAHTERA ABADI',
        'direktur' => 'Arjuma',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Mandala',
        'nama_bumdes' => 'BUM DESA MAJU BERSAMA',
        'direktur' => 'Syaiful Anwar',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Manding Daya',
        'nama_bumdes' => 'BUM DESA MITRA USAHA JAYA',
        'direktur' => 'Fawaid Fatahoni',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Manding Laok',
        'nama_bumdes' => 'BUM DESA PUTRA HARAPAN',
        'direktur' => 'Nur Yasin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Manding Timur',
        'nama_bumdes' => 'BUM DESA MAKMUR JAYA',
        'direktur' => 'Apri Alumansyah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Mantajun',
        'nama_bumdes' => 'BUM DESA MAWAR',
        'direktur' => 'Choirul Unam',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Marengan Daya',
        'nama_bumdes' => 'BUM DESA SEMARU',
        'direktur' => 'Hidayatur Ainur R.',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Marengan Laok',
        'nama_bumdes' => 'BUM DESA PERMATA',
        'direktur' => 'Henky Rorin Tanando',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Masaran',
        'nama_bumdes' => 'BUM DESA BAROKAH',
        'direktur' => 'lilis tiarini',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Matanair',
        'nama_bumdes' => 'BUM DESA MAKMUR JAYA',
        'direktur' => 'Muh. Faizal Shandy',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Meddelan',
        'nama_bumdes' => 'BUM DESA MEDDELAN BAROKAH', 
        'direktur' => 'Asmuni',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Moncek Barat',
        'nama_bumdes' => 'BUM DESA MUTIARA INDAH',
        'direktur' => 'Ahmad Zainurridha',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Moncek Tengah',
        'nama_bumdes' => 'BUM DESA MANDIRI',
        'direktur' => 'Aditia Putra Abi Safik',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Moncek Timur',
        'nama_bumdes' => 'BUM DESA SERA BERKAT',
        'direktur' => 'Maulidi Amsi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Montorna',
        'nama_bumdes' => 'BUM DESA SATUPADU',
        'direktur' => 'Mansur',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Muangan',
        'nama_bumdes' => 'BUM DESA GRAHA ARTHA MANDIRI',
        'direktur' => 'Surahmo',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Nambakor',
        'nama_bumdes' => 'BUM DESA GAJAH MADA',
        'direktur' => 'Saifurrahman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Nonggunong',
        'nama_bumdes' => 'BUM DESA PASTI JAYA',
        'direktur' => 'Yasir',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Nyabakan Barat',
        'nama_bumdes' => 'BUM DESA SUMBER REJEKI',
        'direktur' => 'Moh. Hariyanto',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Nyabakan Timur',
        'nama_bumdes' => 'BUM DESA SUMBER REJEKI',
        'direktur' => 'Nur Salim',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Nyamplong',
        'nama_bumdes' => 'BUM DESA MAWAR NYAMPLONG SEJAHTERA', 
        'direktur' => 'Nur Haili',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Nyapar',
        'nama_bumdes' => 'BUM DESA NYAPAR JAYA', 
        'direktur' => 'Hj. Yuniwati',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pabean',
        'nama_bumdes' => 'BUM DESA USAHA RAKYAT SEJAHTERA',
        'direktur' => 'Hasana',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Paberasan',
        'nama_bumdes' => 'BUM DESA KUDA PUTIH',
        'direktur' => 'Aji Firdaus',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pabian',
        'nama_bumdes' => 'BUM DESA PABIAN BERSATU', 
        'direktur' => 'Yenni Ratna Movida',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Padangdangan',
        'nama_bumdes' => 'BUM DESA SUPER MANTAP',
        'direktur' => 'Saheruddin',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Padike',
        'nama_bumdes' => 'BUM DESA SUMBER ATOM',
        'direktur' => 'Khairul Arif',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Pagar Batu',
        'nama_bumdes' => 'BUM DESA HARAPAN BAHARI',
        'direktur' => 'Agus Rifandi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pagerungan Besar',
        'nama_bumdes' => 'BUM DESA PAGERUNGAN JAYA',
        'direktur' => 'Husin Jamil',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Pagerungan Kecil',
        'nama_bumdes' => 'BUM DESA PADDALLEANTE',
        'direktur' => 'Ruslan, SH',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Pajanangger',
        'nama_bumdes' => 'BUM DESA NYOGO TOLE',
        'direktur' => 'Moh. Luqman Saidy',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pakamban Daya',
        'nama_bumdes' => 'BUM DESA BAROKAH',
        'direktur' => 'M. Wakid',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Pakamban Laok',
        'nama_bumdes' => 'BUM DESA BAROKAH',
        'direktur' => 'Ainul Yakin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pakandangan Barat',
        'nama_bumdes' => 'BUM DESA MAKMUR BERSAMA',
        'direktur' => 'Ulvina Qurrotu A yuni',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pakandangan Sangra',
        'nama_bumdes' => 'BUM DESA BUNGA INDAH',
        'direktur' => '-',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Pakandangan Tengah',
        'nama_bumdes' => 'BUM DESA BINA SEJAHTERA',
        'direktur' => 'Turit Hanafi',
        'status_hukum' => 'Perbaikan Nama',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Pakondang',
        'nama_bumdes' => 'BUM DESA POJUR JAYA',
        'direktur' => 'Akhmad Bunyani',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Palasa',
        'nama_bumdes' => 'BUM DESA PUTRA PALASA',
        'direktur' => 'Makmur Jaya',
        'status_hukum' => 'Perbaikan Nama',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Paliat',
        'nama_bumdes' => 'BUM DESA TIRTA MANDIRI',
        'direktur' => 'Sahriyanto',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => "Palo'lo'an",
        'nama_bumdes' => 'BUM DESA MACAN ALAM',
        'direktur' => 'Mochamad Lukman',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Palongan',
        'nama_bumdes' => 'BUM DESA AMANGKURAT',
        'direktur' => 'Abu Suhairi',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Pamolokan',
        'nama_bumdes' => 'BUM DESA PALAPA BARU',
        'direktur' => 'Beni Arie Setyabudi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Panagan',
        'nama_bumdes' => 'BUM DESA MULYA ABADI',
        'direktur' => 'Agus Purnomo',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pananggungan',
        'nama_bumdes' => 'BUM DESA PUTRI KENCANA',
        'direktur' => 'Rahmatun',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Panaongan',
        'nama_bumdes' => 'BUM DESA BENTENG JAYA',
        'direktur' => 'Nuruddin Holid Efendi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pancor',
        'nama_bumdes' => 'BUM DESA SUKSES JAYA PANCOR SEJAHTERA',
        'direktur' => 'Imam Bukhari',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Pandeman',
        'nama_bumdes' => 'BUM DESA PANDEMAN SEJAHTERA',
        'direktur' => 'Rahikim Makhtum',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pandian',
        'nama_bumdes' => 'BUM DESA TAMBAK KERATON',
        'direktur' => 'Moh. Salehoddin',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pangarangan',
        'nama_bumdes' => 'BUM DESA KEJORA',
        'direktur' => 'Ach. Syaiful',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Parsanga',
        'nama_bumdes' => 'BUM DESA CAMAR',
        'direktur' => 'Hartono',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Paseraman',
        'nama_bumdes' => 'BUM DESA BANGKIT MAJU BERSAMA PASERAMAN SEJAHTERA',
        'direktur' => 'Ikhwanudin, S.H',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Pasongsongan',
        'nama_bumdes' => 'BUM DESA JAYA SAMUDRA',
        'direktur' => 'Suhriyanto',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Patean',
        'nama_bumdes' => 'BUM DESA BERKARYA',
        'direktur' => 'Hendrik',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Payudan Daleman',
        'nama_bumdes' => 'BUM DESA PUTRIKUNING',
        'direktur' => 'Rizal Wahyudi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Payudan Dundang',
        'nama_bumdes' => 'BUM DESA AL-BAROKAH',
        'direktur' => 'Nurul Arifin',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Payudan Karangsokon',
        'nama_bumdes' => 'BUM DESA ABDI NUSA',
        'direktur' => 'Holil, S.Thi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Payudan Nangger',
        'nama_bumdes' => 'BUM DESA JHEBU',
        'direktur' => 'Ach. Samlan',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Poja',
        'nama_bumdes' => 'BUM DESA NUR HIKMAH',
        'direktur' => 'Kusniya',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pordapor',
        'nama_bumdes' => 'BUM DESA IDAMAN',
        'direktur' => '-',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Poreh',
        'nama_bumdes' => 'BUM DESA MURAH REJEKI',
        'direktur' => 'Dian Aminda',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Poteran',
        'nama_bumdes' => 'BUM DESA POTRA KONENG',
        'direktur' => 'Imam Sarbini',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Poteran',
        'nama_bumdes' => 'BUM DESA ARRIZQI',
        'direktur' => 'Karim',
        'status_hukum' => 'Perbaikan Nama',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Pragaan Daya',
        'nama_bumdes' => 'BUM DESA PRADA SEJAHTERA',
        'direktur' => 'M. Wakid',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Pragaan Laok',
        'nama_bumdes' => 'BUM DESA TARESNAH',
        'direktur' => 'Akh. Rasyidi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Prambanan',
        'nama_bumdes' => 'BUM DESA SUMBER MAKMUR',
        'direktur' => 'Sadwan',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Prancak',
        'nama_bumdes' => 'BUM DESA PRANCAK MAKMUR',
        'direktur' => 'Moh. Sa edi Kirom',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Prenduan',
        'nama_bumdes' => 'BUM DESA MERPATI',
        'direktur' => 'Wahdi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Rajun',
        'nama_bumdes' => 'BUM DESA BUNGA DAHLIA',
        'direktur' => 'Ostman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Rombasan',
        'nama_bumdes' => 'BUM DESA CAHAYA LESTARI',
        'direktur' => 'Rofiq Romadlan',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Romben Barat',
        'nama_bumdes' => 'BUM DESA GAJAH MADA',
        'direktur' => 'Aisyah Bela',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Romben Guna',
        'nama_bumdes' => 'BUM DESA BAROKAH',
        'direktur' => 'Jasilatul Khotimah',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Romben Rana',
        'nama_bumdes' => 'BUM DESA RANA WIJAYA',
        'direktur' => 'Hodaifah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Rombiya Barat',
        'nama_bumdes' => 'BUM DESA KENCANA',
        'direktur' => 'Ilyasi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Rombiya Timur',
        'nama_bumdes' => 'BUM DESA PURNAMA',
        'direktur' => '-',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Rosong',
        'nama_bumdes' => 'BUM DESA MAJU MAKMUR',
        'direktur' => 'Mudiha',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Rubaru',
        'nama_bumdes' => 'BUM DESA HARAPAN BARU',
        'direktur' => 'Moh. Kholid',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sabunten',
        'nama_bumdes' => 'BUM DESA JAYA',
        'direktur' => 'Wahab',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sadulang',
        'nama_bumdes' => 'BUM DESA PERSADA',
        'direktur' => 'Ustman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BELUM ISI',
    ],
    [
        'desa' => 'Sakala',
        'nama_bumdes' => 'BUM DESA BATU MA DENGKENG',
        'direktur' => 'Moh. Fatang',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sambakati',
        'nama_bumdes' => 'BUM DESA SEMBAH BAKTI',
        'direktur' => 'Ach. Miftahul Anwar',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Saobi',
        'nama_bumdes' => 'BUM DESA SAMUDRA JAYA',
        'direktur' => 'Ainur Halik',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Sapeken',
        'nama_bumdes' => 'BUM DESA MANDIRI',
        'direktur' => 'Rusman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Saroka',
        'nama_bumdes' => 'BUM DESA SEKAR SARI',
        'direktur' => 'Hardiono',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Saronggi',
        'nama_bumdes' => 'BUM DESA KERMATA',
        'direktur' => 'Agus Wedi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Saseel',
        'nama_bumdes' => 'BUM DESA SASEEL JAYA',
        'direktur' => 'Boby Anwar',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Saur Saebus',
        'nama_bumdes' => 'BUM DESA SEJAHTERA',
        'direktur' => 'Muhammad Ramlah',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BELUM ISI',
    ],
    [
        'desa' => 'Sawah Sumur',
        'nama_bumdes' => 'BUM DESA SAWAH SUMUR BANGKIT',
        'direktur' => 'Fauzi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Semaan',
        'nama_bumdes' => 'BUM DESA MAJU JAYA',
        'direktur' => 'Mohamad Fahrul',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sendang',
        'nama_bumdes' => 'BUM DESA AMANAH',
        'direktur' => 'Mohammad Ra i',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sendir',
        'nama_bumdes' => 'BUM DESA SUMBER REJEKI',
        'direktur' => 'Sucipto Winarki',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Sentol Daya',
        'nama_bumdes' => 'BUM DESA PERMATA',
        'direktur' => 'Ach. Junaidi, S.H., M.Si',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sentol Laok',
        'nama_bumdes' => 'BUM DESA MAKMUR',
        'direktur' => 'M. Yunus',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sepanjang',
        'nama_bumdes' => 'BUM DESA PANJI SURI',
        'direktur' => 'Agus Salim',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Sera Barat',
        'nama_bumdes' => 'BUM DESA PUTRA DESA',
        'direktur' => 'Moh. Fahri',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Sera Tengah',
        'nama_bumdes' => 'BUM DESA SUMBER MAKMUR',
        'direktur' => 'Eko Purnomo',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
     [
        'desa' => 'Sera Timur',
        'nama_bumdes' => '-',
        'direktur' => '-',
        'status_hukum' => 'Belum Mendaftar Nama dan Badan Hukum',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Sergang',
        'nama_bumdes' => 'BUM DESA PANTURA',
        'direktur' => 'Nur Aini',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Slopeng',
        'nama_bumdes' => 'BUM DESA LEBAH MADU',
        'direktur' => 'Sutrisno',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Soddara',
        'nama_bumdes' => 'BUM DESA SATARETAN',
        'direktur' => 'Akhmad Suhalis',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sogian',
        'nama_bumdes' => 'BUM DESA SOFWAN',
        'direktur' => 'Ubaidillah Makki',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sokaramme Paseser',
        'nama_bumdes' => 'BUM DESA SUMBER JAYA',
        'direktur' => 'Sumahwar',
        'status_hukum' => 'Perbaikan Badan Hukum',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Sokaramme Timur',
        'nama_bumdes' => 'BUM DESA BUNGA MELATI',
        'direktur' => 'Jamilatul Qomariya',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Somber',
        'nama_bumdes' => 'BUM DESA SUMBER REJEKI',
        'direktur' => 'Nur Fauzani Gustama',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Sonok',
        'nama_bumdes' => 'BUM DESA TIGA SAUDARA',
        'direktur' => 'Senni Aida',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Sumbernangka',
        'nama_bumdes' => 'BUM DESA GUMMANG JAYA',
        'direktur' => 'Misnawi',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BELUM DI ISI',
    ],
    [
        'desa' => 'Talaga',
        'nama_bumdes' => 'BUM DESA BERKAH',
        'direktur' => 'Moh. Ali Tsabit',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Talaga',
        'nama_bumdes' => 'BUM DESA TELAGA BENING',
        'direktur' => 'Mohammad Susiyanto',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Talang',
        'nama_bumdes' => 'BUM DESA NAGA MERAH',
        'direktur' => 'Kuzairi',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Talango',
        'nama_bumdes' => 'BUM DESA MAKMUR JAYA',
        'direktur' => 'Mohamad Novel',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Taman Sare',
        'nama_bumdes' => 'BUM DESA MEKAR SARI',
        'direktur' => 'Bunawi',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Tambaagung Ares',
        'nama_bumdes' => 'BUM DESA SUMBER PAYUNG',
        'direktur' => 'Sayrafi, S.Pd',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tambaagung Barat',
        'nama_bumdes' => 'BUM DESA BUNGA DESA',
        'direktur' => 'Syamsul Arifin',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tambaagung Tengah',
        'nama_bumdes' => 'BUM DESA MAHKOTA',
        'direktur' => 'Lutfiyah',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'MAJU',
    ],
    [
        'desa' => 'Tambaagung Timur',
        'nama_bumdes' => 'BUM DESA JUNJUNG DRAJAD',
        'direktur' => 'Nailur Rahman',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tambaksari',
        'nama_bumdes' => 'BUM DESA BERGARANSI',
        'direktur' => 'Syarif Hidayatullah',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tambuko',
        'nama_bumdes' => 'BUM DESA MAKMUR SEJAHTERA',
        'direktur' => 'Fathol Bari',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Tamidung',
        'nama_bumdes' => 'BUM DESA BAROKAH',
        'direktur' => '-',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tanah Merah',
        'nama_bumdes' => 'BUM DESA ABADI',
        'direktur' => 'Samsul Arifin',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Tanamerah',
        'nama_bumdes' => 'BUM DESA RAMPAK NAONG',
        'direktur' => 'Andi Suyono',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tanjung',
        'nama_bumdes' => 'BUM DESA PERMATA SARI',
        'direktur' => 'Amanur Rahim',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tanjung Kiaok',
        'nama_bumdes' => 'BUM DESA CAHAYA',
        'direktur' => 'Abd. Rahman',
        'status_hukum' => 'Dokumen Badan Hukum Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tarebung',
        'nama_bumdes' => 'BUM DESA JAYA BAHTERA',
        'direktur' => 'Muhamad',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tarogan',
        'nama_bumdes' => 'BUM DESA BINTANG HARAPAN',
        'direktur' => 'Nur Azizah',
        'status_hukum' => 'Badan Hukum Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Tembayangan',
        'nama_bumdes' => 'BUM DESA MATAHARI TERBIT',
        'direktur' => 'Marsuyan',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tengedan',
        'nama_bumdes' => 'BUM DESA AROBY',
        'direktur' => 'Naufal Efendi',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Timur Jang-Jang',
        'nama_bumdes' => 'BUM DESA LAUTAN ASMARA',
        'direktur' => 'Muhammad Sari',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BERKEMBANG',
    ],
    [
        'desa' => 'Tonduk',
        'nama_bumdes' => 'BUM DESA CINDAI',
        'direktur' => 'Aidi Ma Mun',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'PEMULA',
    ],
    [
        'desa' => 'Torbang',
        'nama_bumdes' => 'BUM DESA SA ATE',
        'direktur' => 'Masruji',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Torjek',
        'nama_bumdes' => 'BUM DESA JAYA MANDIRI',
        'direktur' => 'Arif Rahman',
        'status_hukum' => 'Nama Terverifikasi',
        'klasifikasi' => 'BELUM ISI DDC',
    ],
    [
        'desa' => 'Totosan',
        'nama_bumdes' => 'BUM DESA HARAPAN BERSAMA',
        'direktur' => 'Satrawi',
        'status_hukum' => 'Perbaikan Dokumen Badan Hukum',
        'klasifikasi' => 'BERKEMBANG',
    ],
        ];

        foreach ($data as $item) {

    $desa = DB::table('desas')
        ->where('nama_desa', $item['desa'])
        ->first();

    if (!$desa) {
        continue; 
    }

    DB::table('bumdes')->updateOrInsert(
        
        [
            'desa_id' => $desa->id,
            'nama_bumdes' => trim($item['nama_bumdes'] ?? '-'),

        ],
        
        [
            'direktur'     => $item['direktur'] ?? '-',
            'status_hukum' => $item['status_hukum'] ?? '-',
            'klasifikasi'  => $item['klasifikasi'] ?? '-',
            'updated_at' => now(),
            'created_at' => now(),
        ]
    );
}

    }
}
