<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DesaSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'Ambunten' => [
                'Ambunten Barat',
                'Ambunten Tengah',
                'Ambunten Timur',
                'Belluk Ares',
                'Belluk Kenek',
                'Belluk Raja',
                'Bukabu',
                'Campor Barat',
                'Campor Timur',
                'Keles',
                'Sogian',
                'Tambaagung Ares',
                'Tambaagung Barat',
                'Tambaagung Tengah',
                'Tambaagung Timur'
            ],
            'Arjasa' => [
                'Angkatan',
                'Angon-angon',
                'Arjasa',
                'Bilis-Bilis',
                'Buddi',
                'Duko',
                'Gelaman',
                'Kalikatak',
                'Kalinganyar',
                'Kalisangka',
                'Kolo-Kolo',
                'Laok Jang-Jang',
                'Pabean',
                'Pajanangger',
                'Pandeman',
                'Paseraman',
                'Sambakati',
                'Sawah Sumur',
                'Sumbernangka',
            ],
            'Batang Batang' => [
                'Banuaju Barat',
                'Banuaju Timur',
                'Batang-Batang Daya',
                'Batang-Batang Laok',
                'Bilangan',
                'Dapenda',
                'Jangkong',
                'Jenangger',
                'Kolpo',
                'Legung Barat',
                'Legung Timur',
                'Lombang',
                'Nyabakan Barat',
                'Nyabakan Timur',
                'Tamidung',
                'Totosan',
            ],
            'Batuan' => [
                'Babbalan',
                'Batuan',
                'Gedungan',
                'Galugur',
                'Gunggung',
                'Patean',
                'Torbang',
            ],
            'Batuputih' => [
                'Aengmerah',
                'Badur',
                'Bantelan',
                'Batuputih Daya',
                'Batuputih Kenek',
                'Batuputih Laok',
                'Bulla\'an',
                'Gedang-Gedang',
                'Juruan Daya',
                'Juruan Laok',
                'Larangan Barma',
                'Larangan Kerta',
                'Sergang',
                'Tengedan',
            ],
            'Bluto' => [
                'Aeng Baja Kenek',
                'Aeng Baja Raja',
                'Aeng Dake',
                'Bluto',
                'Bumbungan',
                'Errabu',
                'Gilang',
                'Gingging',
                'Guluk Manjung',
                'Kapedi',
                'Karang Campaka',
                'Lobuk',
                'Masaran',
                'Pakandangan Barat',
                'Pakandangan Sangra',
                'Pakandangan Tengah',
                'Palongan',
                'Sera Barat',
                'Sera Tengah',
                'Sera Timur',
            ],
            'Dasuk' => [
                'Batubellah Barat',
                'Batubellah Timur',
                'Bates',
                'Bringin',
                'Dasuk Barat',
                'Dasuk Laok',
                'Dasuk Timur',
                'Jelbudan',
                'Kecer',
                'Kerta Barat',
                'Kerta Timur',
                'Mantajun',
                'Nyapar',
                'Semaan',
                'Slopeng',
            ],
            'Dungkek' => [
                'Bancamara',
                'Banra\'as',
                'Bicabbi',
                'Bunpenang',
                'Bungin-Bungin',
                'Candi',
                'Dungkek',
                'Jadung',
                'Lapa Daya',
                'Lapa Laok',
                'Lapa Taman',
                'Romben Barat',
                'Romben Guna',
                'Romben Rana',
                'Taman Sare',
            ],
            'Ganding' => [
                'Bataal Barat',
                'Bataal Timur',
                'Billapora Barat',
                'Billapora Timur',
                'Gadu Barat',
                'Gadu Timur',
                'Ganding',
                'Ketawang Daleman',
                'Ketawang Karay',
                'Ketawang Larangan',
                'Ketawang Parebaan',
                'Rombiya Barat',
                'Rombiya Timur',
                'Talaga',
            ],
            'Gapura' => [
                'Andulang',
                'Baban',
                'Banjar Barat',
                'Banjar Timur',
                'Batudinding',
                'Braji',
                'Gapura Barat',
                'Gapura Tengah',
                'Gapura Timur',
                'Gersik Putih',
                'Grujugan',
                'Karangbudi',
                'Longos',
                'Mandala',
                'Palo\'lo\'an',
                'Panagan',
                'Poja',
            ],
            'Gayam' => [
                'Gayam',
                'Gendang Barat',
                'Gendang Timur',
                'Jambuir',
                'Kalowang',
                'Karang Tengah',
                'Nyamplong',
                'Pancor',
                'Prambanan',
                'Tarebung',
            ],
            'Giligenting' => [
                'Aenganyar',
                'Banbaru',
                'Banmaleng',
                'Bringsang',
                'Galis',
                'Gedugan',
                'Jate',
                'Lombang',
            ],
            'Guluk-Guluk' => [
                'Bakeong',
                'Bragung',
                'Batuampar',
                'Guluk-guluk',
                'Ketawang Laok',
                'Pananggungan',
                'Payudan Dundang',
                'Payudan Daleman',
                'Payudan Karangsokon',
                'Payudan Nangger',
                'Pordapor',
                'Tambuko',
            ],
            'Kalianget' => [
                'Kalianget Barat',
                'Kalianget Timur',
                'Kalimook',
                'Karanganyar',
                'Kertasada',
                'Marengan Laok',
                'Pinggirpapas',
            ],
            'Kangayan' => [
                'Batuputih',
                'Cangkramaan',
                'Daandung',
                'Jukong-Jukong',
                'Kangayan',
                'Saobi',
                'Tembayangan',
                'Timur Jang-Jang',
                'Torjek',
            ],
            'Kota Sumenep' => [
                'Bangkal',
                'Kacongan',
                'Kebunagung',
                'Kebunan',
                'Kolor',
                'Marengan Daya',
                'Paberasan',
                'Pabian',
                'Pamolokan',
                'Pandian',
                'Pangarangan',
                'Parsanga',
            ],
            'Lenteng' => [
                'Banaresep Barat',
                'Banaresep Timur',
                'Billapora Rebba',
                'Cangkreng',
                'Daramista',
                'Ellak Daya',
                'Ellak Laok',
                'Jambu',
                'Kambingan Barat',
                'Lembung Barat',
                'Lembung Timur',
                'Lenteng Barat',
                'Lenteng Timur',
                'Meddelan',
                'Moncek Barat',
                'Moncek Tengah',
                'Moncek Timur',
                'Poreh',
                'Sendir',
                'Tarogan',
            ],
            'Manding' => [
                'Gadding',
                'Giring',
                'Gunung Kembar',
                'Jaba\'an',
                'Kasengan',
                'Lalangon',
                'Lanjuk',
                'Manding Daya',
                'Manding Laok',
                'Manding Timur',
                'Tenonan',
            ],
            'Masalembu' => [
                'Kramian',
                'Masakambing',
                'Masalima',
                'Sukajeruk',
            ],
            'Nonggunong' => [
                'Nonggunong',
                'Rosong',
                'Sokaramme Paseser',
                'Sokaramme Timur',
                'Somber',
                'Sonok',
                'Talaga',
                'Tanah Merah',
            ],
            'Pasongsongan' => [
                'Campaka',
                'Lebeng Barat',
                'Lebeng Timur',
                'Montorna',
                'Padangdangan',
                'Panaongan',
                'Pasongsongan',
                'Prancak',
                'Rajun',
                'Soddara',
            ],
            'Pragaan' => [
                'Aeng Panas',
                'Jaddung',
                'Kaduara Timur',
                'Karduluk',
                'Larangan Perreng',
                'Pakamban Daya',
                'Pakamban Laok',
                'Pragaan Daya',
                'Pragaan Laok',
                'Prenduan',
                'Rombasan',
                'Sendang',
                'Sentol Daya',
                'Sentol Laok',
            ],
            'Raas' => [
                'Alas Malang',
                'Brakas',
                'Guwa-Guwa',
                'Jungkat',
                'Karangnangka',
                'Ketupat',
                'Kropoh',
                'Poteran',
                'Tonduk',
            ],
            'Rubaru' => [
                'Banasare',
                'Basoka',
                'Bunbarat',
                'Duko',
                'Kalebengan',
                'Karang Nangka',
                'Mandala',
                'Matanair',
                'Pakondang',
                'Rubaru',
                'Tambaksari',
            ],
            'Sapeken' => [
                'Pagerungan Besar',
                'Pagerungan Kecil',
                'Paliat',
                'Sabunten',
                'Sadulang',
                'Sakala',
                'Sapeken',
                'Saseel',
                'Saur Saebus',
                'Sepanjang',
                'Tanjung Kiaok',
            ],
            'Saronggi' => [
                'Aengtongtong',
                'Juluk',
                'Kambingan Timur',
                'Kebundadap Barat',
                'Kebundadap Timur',
                'Langsar',
                'Muangan',
                'Nambakor',
                'Pagar Batu',
                'Saroka',
                'Saronggi',
                'Talang',
                'Tanjung',
                'Tanamerah',
            ],
            'Talango' => [
                'Cabbiya',
                'Essang',
                'Gapurana',
                'Kombang',
                'Padike',
                'Palasa',
                'Poteran',
                'Talango',
            ],
        ];
        foreach ($data as $namaKecamatan => $desas) {

            $kecamatan = DB::table('kecamatans')
                ->where('nama_kecamatan', $namaKecamatan)
                ->first();

            if (!$kecamatan) {
                continue; // skip kalau kecamatan tidak ditemukan
            }

            foreach ($desas as $desa) {
                DB::table('desas')->insert([
                    'kecamatan_id' => $kecamatan->id,
                    'nama_desa' => $desa,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}